{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggstatsplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggstatsplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggstatsplot/ggstatsplot_{{ version }}.tar.gz
  sha256: f08701a4d73a8157140c98d114d160485c4494d6e32fdb5cc00f236d5f11dc3c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-correlation >=0.8.8
    - r-datawizard >=1.3.0
    - r-dplyr >=1.2.1
    - r-forcats
    - r-ggcorrplot >=0.1.4.1
    - r-ggplot2 >=4.0.2
    - r-ggrepel >=0.9.8
    - r-ggside >=0.4.1
    - r-ggsignif >=0.6.4
    - r-glue >=1.8.0
    - r-insight >=1.4.6
    - r-magrittr >=2.0.4
    - r-paletteer >=1.7.0
    - r-parameters >=0.28.3
    - r-patchwork >=1.3.2
    - r-performance >=0.16.0
    - r-purrr >=1.2.1
    - r-rlang >=1.1.7
    - r-statsexpressions >=1.7.4
    - r-tidyr >=1.3.2
  run:
    - r-base
    - r-correlation >=0.8.8
    - r-datawizard >=1.3.0
    - r-dplyr >=1.2.1
    - r-forcats
    - r-ggcorrplot >=0.1.4.1
    - r-ggplot2 >=4.0.2
    - r-ggrepel >=0.9.8
    - r-ggside >=0.4.1
    - r-ggsignif >=0.6.4
    - r-glue >=1.8.0
    - r-insight >=1.4.6
    - r-magrittr >=2.0.4
    - r-paletteer >=1.7.0
    - r-parameters >=0.28.3
    - r-patchwork >=1.3.2
    - r-performance >=0.16.0
    - r-purrr >=1.2.1
    - r-rlang >=1.1.7
    - r-statsexpressions >=1.7.4
    - r-tidyr >=1.3.2

test:
  commands:
    - $R -e "library('ggstatsplot')"           # [not win]
    - "\"%R%\" -e \"library('ggstatsplot')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/ggstatsplot/
  dev_url: https://github.com/IndrajeetPatil/ggstatsplot
  license: MIT
  summary: "Extension of 'ggplot2', 'ggstatsplot' creates graphics with details from statistical tests included in the plots themselves. It provides an easier API to generate information-rich plots for statistical analysis of continuous (violin plots, scatterplots, histograms, dot plots, dot-and-whisker plots) or categorical
    (pie and bar charts) data. Currently, it supports only the most common types of statistical tests: parametric, nonparametric, robust, and Bayesian versions of t-test/ANOVA, correlation analyses, contingency table analysis, meta-analysis, and regression analyses."
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
